# Generated by Django 4.2.5 on 2023-09-12 23:33

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ExampleModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                (
                    "description",
                    models.CharField(
                        blank=True, default="", max_length=10000, null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Example",
                "verbose_name_plural": "Examples",
            },
        ),
    ]
